# frozen_string_literal: true

source "https://rubygems.org"

#git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "fastlane", require: false
gem "cocoapods", "1.16.2", require: false
