# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
  desc "Build and upload a beta version to TestFlight"
  lane :beta do
    # ensure Homebrew bin is visible to the subshells fastlane spawns
    env_path = 'export PATH="/opt/homebrew/bin:$PATH"'

    sh "#{env_path}; cd .. && flutter pub get"
    sh 'echo "FASTLANE PATH=$PATH"; which pod; pod --version; ruby -v'
    sh "#{env_path}; cd .. && flutter build ipa --release"

    # 3. Upload to TestFlight
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    # If fastlane generated an app_identifier / app-specific config 
    # use those here. Replace with your details:
    app_identifier = "us.antonovich.nextchord" # or whatever your bundle id is
    apple_id       = "thomas@antonovich.us" # not strictly needed if using API key
    app_name       = "NextChord"

    api_key = app_store_connect_api_key(
      key_id: "D28W2YBXS9",
      issuer_id: "a5176732-64f6-441d-8ed0-0db127470dda",
      key_filepath: "../AuthKeys/AuthKey_D28W2YBXS9.p8"
)

    upload_to_testflight(
      ipa: "../build/ios/ipa/nextchord.ipa", # or YourAppName.ipa
      app_identifier: app_identifier,
      skip_waiting_for_build_processing: false,
      # Optional: auto-submit to internal group
      distribute_external: false,
      groups: ["Int"] # if you have groups set up
    )
  end
end
