import Cocoa
import FlutterMacOS

class MainFlutterWindow: NSWindow {
  override func awakeFromNib() {
    let flutterViewController = FlutterViewController()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    // Register Flutter plugins generated by Flutter tooling
    RegisterGeneratedPlugins(registry: flutterViewController)

    // Register custom iCloud Drive plugin so the 'icloud_drive' MethodChannel
    // is available to the Dart side on macOS.
    ICloudDrivePlugin.register(with: flutterViewController.registrar(forPlugin: "ICloudDrivePlugin"))

    super.awakeFromNib()
  }
}
